name: Variables and Arithmetic Operators
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: codeschooluz/build_in_function_test
          token: ${{secrets.TEST_KEY}}
          path: test
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install pytest
        run: |
          pip install pytest
          pip install requests
      - name: Run tests
        run: |
          pytest -v --tb=no -q
        continue-on-error: true
      - name: Natijalar
        run: |
          python test/sendtest.py ${{github.actor}} '${{github.repository}}'
